[tools]
go = "1.27.1"
golangci-lint = "2.14.0"
gotestsum = "1.13.0"
osv-scanner = "2.6.0"
task = "3.54.0"
gofumpt = "0.12.0"
protoc-gen-go = "1.36.12"
buf = "1.73.0"
"npm:playwright" = "1.63.0"
air = "1.67.4"
protoc-gen-connect-go = "1.21.0"
